@ECHO  OFF
IF "%1" == "java" (protoc -Iprotos\im\basic -Iprotos\im\message --java_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --java_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "cpp" (protoc -Iprotos\im\basic -Iprotos\im\message --cpp_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --cpp_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "js" (protoc -Iprotos\im\basic -Iprotos\im\message --js_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --js_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "objc" (protoc -Iprotos\im\basic -Iprotos\im\message --objc_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --objc_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "php" (protoc -Iprotos\im\basic -Iprotos\im\message --php_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --php_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "python" (protoc -Iprotos\im\basic -Iprotos\im\message --python_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --python_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "ruby" (protoc -Iprotos\im\basic -Iprotos\im\message --ruby_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --ruby_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "go" (protoc -Iprotos\im\basic -Iprotos\im\message --go_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --go_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
IF "%1" == "csharp" (protoc -Iprotos\im\basic -Iprotos\im\message --csharp_out=.\Models\im protos\im\basic\*.proto protos\im\message\*.proto & protoc -Iprotos\zt.live.interactive --csharp_out=.\Models protos\zt.live.interactive\*.proto) ELSE ^
ECHO Please enter output format: java/cpp/js/objc/php/python/ruby/csharp/go(need install google.golang.org/protobuf/cmd/protoc-gen-go)