// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SharePlatform.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu {

  /// <summary>Holder for reflection information generated from SharePlatform.proto</summary>
  public static partial class SharePlatformReflection {

    #region Descriptor
    /// <summary>File descriptor for SharePlatform.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SharePlatformReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNTaGFyZVBsYXRmb3JtLnByb3RvEgpBY0Z1bkRhbm11KssCCg1TaGFyZVBs",
            "YXRmb3JtEhkKFWtTaGFyZVBsYXRmb3JtSW52YWxpZBAAEhgKFGtTaGFyZVBs",
            "YXRmb3JtV2VjaGF0EAESHwoba1NoYXJlUGxhdGZvcm1XZWNoYXRNb21lbnRz",
            "EAISFAoQa1NoYXJlUGxhdGZvcm1RURADEhcKE2tTaGFyZVBsYXRmb3JtUXpv",
            "bmUQBBIXChNrU2hhcmVQbGF0Zm9ybVdlaWJvEAUSGgoWa1NoYXJlUGxhdGZv",
            "cm1LdWFpc2hvdRAGEhoKFmtTaGFyZVBsYXRmb3JtRmFjZWJvb2sQBxIZChVr",
            "U2hhcmVQbGF0Zm9ybVR3aXR0ZXIQCBIYChRrU2hhcmVQbGF0Zm9ybUdvb2ds",
            "ZRAJEhcKE2tTaGFyZVBsYXRmb3JtS2FrYW8QChIWChJrU2hhcmVQbGF0Zm9y",
            "bVphbG8QC2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AcFunDanmu.SharePlatform), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SharePlatform {
    [pbr::OriginalName("kSharePlatformInvalid")] KSharePlatformInvalid = 0,
    [pbr::OriginalName("kSharePlatformWechat")] KSharePlatformWechat = 1,
    [pbr::OriginalName("kSharePlatformWechatMoments")] KSharePlatformWechatMoments = 2,
    [pbr::OriginalName("kSharePlatformQQ")] KSharePlatformQq = 3,
    [pbr::OriginalName("kSharePlatformQzone")] KSharePlatformQzone = 4,
    [pbr::OriginalName("kSharePlatformWeibo")] KSharePlatformWeibo = 5,
    [pbr::OriginalName("kSharePlatformKuaishou")] KSharePlatformKuaishou = 6,
    [pbr::OriginalName("kSharePlatformFacebook")] KSharePlatformFacebook = 7,
    [pbr::OriginalName("kSharePlatformTwitter")] KSharePlatformTwitter = 8,
    [pbr::OriginalName("kSharePlatformGoogle")] KSharePlatformGoogle = 9,
    [pbr::OriginalName("kSharePlatformKakao")] KSharePlatformKakao = 10,
    [pbr::OriginalName("kSharePlatformZalo")] KSharePlatformZalo = 11,
  }

  #endregion

}

#endregion Designer generated code
