// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GroupCreateResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Cloud.Message {

  /// <summary>Holder for reflection information generated from GroupCreateResponse.proto</summary>
  public static partial class GroupCreateResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for GroupCreateResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GroupCreateResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlHcm91cENyZWF0ZVJlc3BvbnNlLnByb3RvEhtBY0Z1bkRhbm11LkltLkNs",
            "b3VkLk1lc3NhZ2UaD0dyb3VwSW5mby5wcm90bxoRR3JvdXBNZW1iZXIucHJv",
            "dG8aEFN5bmNDb29raWUucHJvdG8i0QEKE0dyb3VwQ3JlYXRlUmVzcG9uc2US",
            "DwoHZ3JvdXBJZBgBIAEoCRI5Cglncm91cEluZm8YAiABKAsyJi5BY0Z1bkRh",
            "bm11LkltLkNsb3VkLk1lc3NhZ2UuR3JvdXBJbmZvEjkKB21lbWJlcnMYAyAD",
            "KAsyKC5BY0Z1bkRhbm11LkltLkNsb3VkLk1lc3NhZ2UuR3JvdXBNZW1iZXIS",
            "MwoKc3luY0Nvb2tpZRgEIAEoCzIfLkFjRnVuRGFubXUuSW0uQmFzaWMuU3lu",
            "Y0Nvb2tpZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AcFunDanmu.Im.Cloud.Message.GroupInfoReflection.Descriptor, global::AcFunDanmu.Im.Cloud.Message.GroupMemberReflection.Descriptor, global::AcFunDanmu.Im.Basic.SyncCookieReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AcFunDanmu.Im.Cloud.Message.GroupCreateResponse), global::AcFunDanmu.Im.Cloud.Message.GroupCreateResponse.Parser, new[]{ "GroupId", "GroupInfo", "Members", "SyncCookie" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GroupCreateResponse : pb::IMessage<GroupCreateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GroupCreateResponse> _parser = new pb::MessageParser<GroupCreateResponse>(() => new GroupCreateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GroupCreateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AcFunDanmu.Im.Cloud.Message.GroupCreateResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GroupCreateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GroupCreateResponse(GroupCreateResponse other) : this() {
      groupId_ = other.groupId_;
      groupInfo_ = other.groupInfo_ != null ? other.groupInfo_.Clone() : null;
      members_ = other.members_.Clone();
      syncCookie_ = other.syncCookie_ != null ? other.syncCookie_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GroupCreateResponse Clone() {
      return new GroupCreateResponse(this);
    }

    /// <summary>Field number for the "groupId" field.</summary>
    public const int GroupIdFieldNumber = 1;
    private string groupId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GroupId {
      get { return groupId_; }
      set {
        groupId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groupInfo" field.</summary>
    public const int GroupInfoFieldNumber = 2;
    private global::AcFunDanmu.Im.Cloud.Message.GroupInfo groupInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AcFunDanmu.Im.Cloud.Message.GroupInfo GroupInfo {
      get { return groupInfo_; }
      set {
        groupInfo_ = value;
      }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::AcFunDanmu.Im.Cloud.Message.GroupMember> _repeated_members_codec
        = pb::FieldCodec.ForMessage(26, global::AcFunDanmu.Im.Cloud.Message.GroupMember.Parser);
    private readonly pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.Message.GroupMember> members_ = new pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.Message.GroupMember>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.Message.GroupMember> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "syncCookie" field.</summary>
    public const int SyncCookieFieldNumber = 4;
    private global::AcFunDanmu.Im.Basic.SyncCookie syncCookie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AcFunDanmu.Im.Basic.SyncCookie SyncCookie {
      get { return syncCookie_; }
      set {
        syncCookie_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GroupCreateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GroupCreateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GroupId != other.GroupId) return false;
      if (!object.Equals(GroupInfo, other.GroupInfo)) return false;
      if(!members_.Equals(other.members_)) return false;
      if (!object.Equals(SyncCookie, other.SyncCookie)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GroupId.Length != 0) hash ^= GroupId.GetHashCode();
      if (groupInfo_ != null) hash ^= GroupInfo.GetHashCode();
      hash ^= members_.GetHashCode();
      if (syncCookie_ != null) hash ^= SyncCookie.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GroupId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GroupId);
      }
      if (groupInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GroupInfo);
      }
      members_.WriteTo(output, _repeated_members_codec);
      if (syncCookie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SyncCookie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GroupId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GroupId);
      }
      if (groupInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GroupInfo);
      }
      members_.WriteTo(ref output, _repeated_members_codec);
      if (syncCookie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SyncCookie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GroupId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupId);
      }
      if (groupInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GroupInfo);
      }
      size += members_.CalculateSize(_repeated_members_codec);
      if (syncCookie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SyncCookie);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GroupCreateResponse other) {
      if (other == null) {
        return;
      }
      if (other.GroupId.Length != 0) {
        GroupId = other.GroupId;
      }
      if (other.groupInfo_ != null) {
        if (groupInfo_ == null) {
          GroupInfo = new global::AcFunDanmu.Im.Cloud.Message.GroupInfo();
        }
        GroupInfo.MergeFrom(other.GroupInfo);
      }
      members_.Add(other.members_);
      if (other.syncCookie_ != null) {
        if (syncCookie_ == null) {
          SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
        }
        SyncCookie.MergeFrom(other.SyncCookie);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GroupId = input.ReadString();
            break;
          }
          case 18: {
            if (groupInfo_ == null) {
              GroupInfo = new global::AcFunDanmu.Im.Cloud.Message.GroupInfo();
            }
            input.ReadMessage(GroupInfo);
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 34: {
            if (syncCookie_ == null) {
              SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
            }
            input.ReadMessage(SyncCookie);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GroupId = input.ReadString();
            break;
          }
          case 18: {
            if (groupInfo_ == null) {
              GroupInfo = new global::AcFunDanmu.Im.Cloud.Message.GroupInfo();
            }
            input.ReadMessage(GroupInfo);
            break;
          }
          case 26: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
          case 34: {
            if (syncCookie_ == null) {
              SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
            }
            input.ReadMessage(SyncCookie);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
