// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GroupStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Cloud.Message {

  /// <summary>Holder for reflection information generated from GroupStatus.proto</summary>
  public static partial class GroupStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for GroupStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GroupStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHcm91cFN0YXR1cy5wcm90bxIbQWNGdW5EYW5tdS5JbS5DbG91ZC5NZXNz",
            "YWdlKj4KC0dyb3VwU3RhdHVzEhcKE1VOS05PV19HUk9VUF9TVEFUVVMQABIJ",
            "CgVWQUxJRBABEgsKB0lOVkFMSUQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AcFunDanmu.Im.Cloud.Message.GroupStatus), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GroupStatus {
    [pbr::OriginalName("UNKNOW_GROUP_STATUS")] UnknowGroupStatus = 0,
    [pbr::OriginalName("VALID")] Valid = 1,
    [pbr::OriginalName("INVALID")] Invalid = 2,
  }

  #endregion

}

#endregion Designer generated code
