// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SessionFolderAddRefRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Cloud.SessionFolder {

  /// <summary>Holder for reflection information generated from SessionFolderAddRefRequest.proto</summary>
  public static partial class SessionFolderAddRefRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for SessionFolderAddRefRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SessionFolderAddRefRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBTZXNzaW9uRm9sZGVyQWRkUmVmUmVxdWVzdC5wcm90bxIhQWNGdW5EYW5t",
            "dS5JbS5DbG91ZC5TZXNzaW9uRm9sZGVyGhZTZXNzaW9uUmVmZXJlbmNlLnBy",
            "b3RvIooBChpTZXNzaW9uRm9sZGVyQWRkUmVmUmVxdWVzdBJNChBzZXNzaW9u",
            "UmVmZXJlbmNlGAEgAygLMjMuQWNGdW5EYW5tdS5JbS5DbG91ZC5TZXNzaW9u",
            "Rm9sZGVyLlNlc3Npb25SZWZlcmVuY2USHQoVdGFyZ2V0U2Vzc2lvbkZvbGRl",
            "cklkGAIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReferenceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderAddRefRequest), global::AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderAddRefRequest.Parser, new[]{ "SessionReference", "TargetSessionFolderId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SessionFolderAddRefRequest : pb::IMessage<SessionFolderAddRefRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionFolderAddRefRequest> _parser = new pb::MessageParser<SessionFolderAddRefRequest>(() => new SessionFolderAddRefRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionFolderAddRefRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderAddRefRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionFolderAddRefRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionFolderAddRefRequest(SessionFolderAddRefRequest other) : this() {
      sessionReference_ = other.sessionReference_.Clone();
      targetSessionFolderId_ = other.targetSessionFolderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionFolderAddRefRequest Clone() {
      return new SessionFolderAddRefRequest(this);
    }

    /// <summary>Field number for the "sessionReference" field.</summary>
    public const int SessionReferenceFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReference> _repeated_sessionReference_codec
        = pb::FieldCodec.ForMessage(10, global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReference.Parser);
    private readonly pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReference> sessionReference_ = new pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReference>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AcFunDanmu.Im.Cloud.SessionFolder.SessionReference> SessionReference {
      get { return sessionReference_; }
    }

    /// <summary>Field number for the "targetSessionFolderId" field.</summary>
    public const int TargetSessionFolderIdFieldNumber = 2;
    private string targetSessionFolderId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetSessionFolderId {
      get { return targetSessionFolderId_; }
      set {
        targetSessionFolderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionFolderAddRefRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionFolderAddRefRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sessionReference_.Equals(other.sessionReference_)) return false;
      if (TargetSessionFolderId != other.TargetSessionFolderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sessionReference_.GetHashCode();
      if (TargetSessionFolderId.Length != 0) hash ^= TargetSessionFolderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      sessionReference_.WriteTo(output, _repeated_sessionReference_codec);
      if (TargetSessionFolderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetSessionFolderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      sessionReference_.WriteTo(ref output, _repeated_sessionReference_codec);
      if (TargetSessionFolderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetSessionFolderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += sessionReference_.CalculateSize(_repeated_sessionReference_codec);
      if (TargetSessionFolderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetSessionFolderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionFolderAddRefRequest other) {
      if (other == null) {
        return;
      }
      sessionReference_.Add(other.sessionReference_);
      if (other.TargetSessionFolderId.Length != 0) {
        TargetSessionFolderId = other.TargetSessionFolderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sessionReference_.AddEntriesFrom(input, _repeated_sessionReference_codec);
            break;
          }
          case 18: {
            TargetSessionFolderId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            sessionReference_.AddEntriesFrom(ref input, _repeated_sessionReference_codec);
            break;
          }
          case 18: {
            TargetSessionFolderId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
