// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SessionListRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Message {

  /// <summary>Holder for reflection information generated from SessionListRequest.proto</summary>
  public static partial class SessionListRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for SessionListRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SessionListRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhTZXNzaW9uTGlzdFJlcXVlc3QucHJvdG8SFUFjRnVuRGFubXUuSW0uTWVz",
            "c2FnZRoQU3luY0Nvb2tpZS5wcm90byJ2ChJTZXNzaW9uTGlzdFJlcXVlc3QS",
            "MwoKc3luY0Nvb2tpZRgBIAEoCzIfLkFjRnVuRGFubXUuSW0uQmFzaWMuU3lu",
            "Y0Nvb2tpZRISCgpjYXRlZ29yeUlkGAIgASgFEhcKD2xvY2FsRGF0YVN0YXR1",
            "cxgDIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AcFunDanmu.Im.Basic.SyncCookieReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AcFunDanmu.Im.Message.SessionListRequest), global::AcFunDanmu.Im.Message.SessionListRequest.Parser, new[]{ "SyncCookie", "CategoryId", "LocalDataStatus" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SessionListRequest : pb::IMessage<SessionListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionListRequest> _parser = new pb::MessageParser<SessionListRequest>(() => new SessionListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AcFunDanmu.Im.Message.SessionListRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionListRequest(SessionListRequest other) : this() {
      syncCookie_ = other.syncCookie_ != null ? other.syncCookie_.Clone() : null;
      categoryId_ = other.categoryId_;
      localDataStatus_ = other.localDataStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionListRequest Clone() {
      return new SessionListRequest(this);
    }

    /// <summary>Field number for the "syncCookie" field.</summary>
    public const int SyncCookieFieldNumber = 1;
    private global::AcFunDanmu.Im.Basic.SyncCookie syncCookie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AcFunDanmu.Im.Basic.SyncCookie SyncCookie {
      get { return syncCookie_; }
      set {
        syncCookie_ = value;
      }
    }

    /// <summary>Field number for the "categoryId" field.</summary>
    public const int CategoryIdFieldNumber = 2;
    private int categoryId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CategoryId {
      get { return categoryId_; }
      set {
        categoryId_ = value;
      }
    }

    /// <summary>Field number for the "localDataStatus" field.</summary>
    public const int LocalDataStatusFieldNumber = 3;
    private int localDataStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LocalDataStatus {
      get { return localDataStatus_; }
      set {
        localDataStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SyncCookie, other.SyncCookie)) return false;
      if (CategoryId != other.CategoryId) return false;
      if (LocalDataStatus != other.LocalDataStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (syncCookie_ != null) hash ^= SyncCookie.GetHashCode();
      if (CategoryId != 0) hash ^= CategoryId.GetHashCode();
      if (LocalDataStatus != 0) hash ^= LocalDataStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (syncCookie_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SyncCookie);
      }
      if (CategoryId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CategoryId);
      }
      if (LocalDataStatus != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LocalDataStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (syncCookie_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SyncCookie);
      }
      if (CategoryId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CategoryId);
      }
      if (LocalDataStatus != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LocalDataStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (syncCookie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SyncCookie);
      }
      if (CategoryId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CategoryId);
      }
      if (LocalDataStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LocalDataStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionListRequest other) {
      if (other == null) {
        return;
      }
      if (other.syncCookie_ != null) {
        if (syncCookie_ == null) {
          SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
        }
        SyncCookie.MergeFrom(other.SyncCookie);
      }
      if (other.CategoryId != 0) {
        CategoryId = other.CategoryId;
      }
      if (other.LocalDataStatus != 0) {
        LocalDataStatus = other.LocalDataStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (syncCookie_ == null) {
              SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
            }
            input.ReadMessage(SyncCookie);
            break;
          }
          case 16: {
            CategoryId = input.ReadInt32();
            break;
          }
          case 24: {
            LocalDataStatus = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (syncCookie_ == null) {
              SyncCookie = new global::AcFunDanmu.Im.Basic.SyncCookie();
            }
            input.ReadMessage(SyncCookie);
            break;
          }
          case 16: {
            CategoryId = input.ReadInt32();
            break;
          }
          case 24: {
            LocalDataStatus = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
