// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SystemUser.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Message {

  /// <summary>Holder for reflection information generated from SystemUser.proto</summary>
  public static partial class SystemUserReflection {

    #region Descriptor
    /// <summary>File descriptor for SystemUser.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemUserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBTeXN0ZW1Vc2VyLnByb3RvEhVBY0Z1bkRhbm11LkltLk1lc3NhZ2UqOQoK",
            "U3lzdGVtVXNlchIWChJrU3lzdGVtVXNlckludmFsaWQQABITCg5TWVNURU1f",
            "VVNFUl9JRBCQTmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AcFunDanmu.Im.Message.SystemUser), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SystemUser {
    [pbr::OriginalName("kSystemUserInvalid")] KSystemUserInvalid = 0,
    [pbr::OriginalName("SYSTEM_USER_ID")] Id = 10000,
  }

  #endregion

}

#endregion Designer generated code
