// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VoiceCallDetailUpdateEvent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AcFunDanmu.Im.Cloud.Voice.Call {

  /// <summary>Holder for reflection information generated from VoiceCallDetailUpdateEvent.proto</summary>
  public static partial class VoiceCallDetailUpdateEventReflection {

    #region Descriptor
    /// <summary>File descriptor for VoiceCallDetailUpdateEvent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VoiceCallDetailUpdateEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBWb2ljZUNhbGxEZXRhaWxVcGRhdGVFdmVudC5wcm90bxIeQWNGdW5EYW5t",
            "dS5JbS5DbG91ZC5Wb2ljZS5DYWxsGhVWb2ljZUNhbGxEZXRhaWwucHJvdG8i",
            "ZgoaVm9pY2VDYWxsRGV0YWlsVXBkYXRlRXZlbnQSSAoPdm9pY2VDYWxsRGV0",
            "YWlsGAEgASgLMi8uQWNGdW5EYW5tdS5JbS5DbG91ZC5Wb2ljZS5DYWxsLlZv",
            "aWNlQ2FsbERldGFpbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetailReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetailUpdateEvent), global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetailUpdateEvent.Parser, new[]{ "VoiceCallDetail" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VoiceCallDetailUpdateEvent : pb::IMessage<VoiceCallDetailUpdateEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VoiceCallDetailUpdateEvent> _parser = new pb::MessageParser<VoiceCallDetailUpdateEvent>(() => new VoiceCallDetailUpdateEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VoiceCallDetailUpdateEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetailUpdateEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceCallDetailUpdateEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceCallDetailUpdateEvent(VoiceCallDetailUpdateEvent other) : this() {
      voiceCallDetail_ = other.voiceCallDetail_ != null ? other.voiceCallDetail_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceCallDetailUpdateEvent Clone() {
      return new VoiceCallDetailUpdateEvent(this);
    }

    /// <summary>Field number for the "voiceCallDetail" field.</summary>
    public const int VoiceCallDetailFieldNumber = 1;
    private global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetail voiceCallDetail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetail VoiceCallDetail {
      get { return voiceCallDetail_; }
      set {
        voiceCallDetail_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VoiceCallDetailUpdateEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VoiceCallDetailUpdateEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VoiceCallDetail, other.VoiceCallDetail)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (voiceCallDetail_ != null) hash ^= VoiceCallDetail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (voiceCallDetail_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VoiceCallDetail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (voiceCallDetail_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VoiceCallDetail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (voiceCallDetail_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VoiceCallDetail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VoiceCallDetailUpdateEvent other) {
      if (other == null) {
        return;
      }
      if (other.voiceCallDetail_ != null) {
        if (voiceCallDetail_ == null) {
          VoiceCallDetail = new global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetail();
        }
        VoiceCallDetail.MergeFrom(other.VoiceCallDetail);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (voiceCallDetail_ == null) {
              VoiceCallDetail = new global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetail();
            }
            input.ReadMessage(VoiceCallDetail);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (voiceCallDetail_ == null) {
              VoiceCallDetail = new global::AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetail();
            }
            input.ReadMessage(VoiceCallDetail);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
